export const CAPABILITY_DEFINITIONS=Object.freeze([
  {id:'run.cancel',title:'Отменить',description:'Отменить текущий Run',inputType:'CANCEL_RUN',scope:'run',inputSchema:{type:'object',properties:{},additionalProperties:false},outputSchema:{accepted:'boolean'},permissions:['run:write'],invocationMode:'ag-ui'},
  {id:'run.retry',title:'Повторить',description:'Создать повторный Run',inputType:'RETRY_RUN',scope:'run',inputSchema:{type:'object',properties:{fromStage:{type:'string'}},additionalProperties:false},outputSchema:{accepted:'boolean'},permissions:['run:create'],invocationMode:'ag-ui'},
  {id:'run.branch',title:'Другой ракурс',description:'Создать ветвь от persisted Run',inputType:'BRANCH_RUN',scope:'run',inputSchema:{type:'object',properties:{fromStage:{type:'string'},role:{type:'string'}},additionalProperties:false},outputSchema:{accepted:'boolean'},permissions:['run:create'],invocationMode:'ag-ui'},
  {id:'run.respond-to-interrupt',title:'Отправить решение',description:'Ответить на canonical HumanInterrupt',inputType:'RESPOND_TO_INTERRUPT',scope:'interrupt',inputSchema:{type:'object',properties:{interruptId:{type:'string'},response:{type:'object'}},required:['interruptId','response'],additionalProperties:false},outputSchema:{accepted:'boolean'},permissions:['run:write'],invocationMode:'ag-ui'},
  {id:'context.add',title:'Добавить контекст',description:'Добавить текстовый контекст и создать research fork',inputType:'ADD_CONTEXT',scope:'run',inputSchema:{type:'object',required:['name','content']},outputSchema:{accepted:'boolean'},permissions:['context:write','run:create'],invocationMode:'ag-ui'},
  {id:'question.change',title:'Изменить вопрос',description:'Создать Run с новым вопросом',inputType:'CHANGE_QUESTION',scope:'run',inputSchema:{type:'object',required:['text']},outputSchema:{accepted:'boolean'},permissions:['run:create'],invocationMode:'ag-ui'}
  ,{id:'research.extend',title:'Исследовать дальше',description:'Продолжить исследование на основе текущих фактов и заданного направления',inputType:'INVOKE_CAPABILITY',scope:'research',inputSchema:{type:'object',properties:{focus:{type:'string',maxLength:500},sourceRef:{type:'string',maxLength:200},evidenceRef:{type:'string',maxLength:200}},additionalProperties:false},outputSchema:{accepted:'boolean',runId:'string'},permissions:['run:create','research:read'],invocationMode:'ag-ui'}
]);
export const ROLE_DISPLAY_CAPABILITIES=Object.freeze({'product-owner':['view.business-impact','view.tradeoff','view.evidence','view.validation'],'cto':['view.architecture','view.reliability','view.migration-risk','view.evidence','view.validation']});
const byId=new Map(CAPABILITY_DEFINITIONS.map(item=>[item.id,Object.freeze({...item})]));
const byInput=new Map(CAPABILITY_DEFINITIONS.map(item=>[item.inputType,item.id]));
export const capabilityForInput=inputType=>byInput.get(inputType)||null;
export const displayCapabilitiesForRole=roleId=>[...(ROLE_DISPLAY_CAPABILITIES[roleId]||['view.source','view.evidence'])];
export function createCapabilityRegistry(){return{get:id=>byId.get(id)||null,list:()=>[...byId.values()],resolveInput:inputType=>{const id=capabilityForInput(inputType);return id?byId.get(id):null;},canInvoke:(id,context={})=>Boolean(byId.has(id)&&capabilityAvailability(id,context).available)};}
export function capabilityAvailability(id,{runStatus,pendingInterrupt=false,hasResearchContext=false,roleId=null}={}){const terminal=['completed','failed','cancelled','interrupted','needs-context'].includes(runStatus);if(id==='run.cancel')return{available:['created','launching','running','waiting-for-human'].includes(runStatus)};if(id==='run.respond-to-interrupt')return{available:runStatus==='waiting-for-human'&&pendingInterrupt};if(id==='research.extend')return{available:terminal&&hasResearchContext&&['product-owner','cto','researcher'].includes(roleId||'product-owner')};if(['run.retry','run.branch','context.add','question.change'].includes(id))return{available:terminal};return{available:false};}
export function capabilityAction(id,{runStatus,pendingInterrupt=false,hasResearchContext=false,roleId=null,inputBinding={},label=null,actionKey=null,inputRequest=null}={}){const capability=byId.get(id);if(!capability)return null;const availability=capabilityAvailability(id,{runStatus,pendingInterrupt,hasResearchContext,roleId});if(!availability.available)return null;return{id:`action:${id}${actionKey?`:${actionKey}`:''}`,capabilityId:id,label:label||capability.title,inputBinding:structuredClone(inputBinding),availability:'available',confirmation:id==='run.cancel'?{kind:'confirmation',message:'Отменить исследование?'}:null,...(inputRequest?{inputRequest:structuredClone(inputRequest)}:{})};}
export function bindCapabilityInvocation(capabilityId,input={},invocationId='invoke-binding-0001'){const capability=byId.get(capabilityId);if(!capability)throw Object.assign(new Error('Unknown capability'),{code:'CAPABILITY_UNKNOWN'});return{type:'INVOKE_CAPABILITY',payload:{capabilityId,invocationId,input:structuredClone(input)}};}
export const capabilityLaunchRequestId=invocationId=>`capability:${String(invocationId)}`;
export function validateCapabilityInput(capabilityId,input){const capability=byId.get(capabilityId);if(!capability)throw Object.assign(new Error('Unknown capability'),{code:'CAPABILITY_UNKNOWN'});if(!input||typeof input!=='object'||Array.isArray(input))throw Object.assign(new Error('Capability input must be an object'),{code:'CAPABILITY_INPUT_INVALID'});const allowed=new Set(Object.keys(capability.inputSchema.properties||{}));if(capability.inputSchema.additionalProperties===false&&Object.keys(input).some(key=>!allowed.has(key)))throw Object.assign(new Error('Capability input has unknown fields'),{code:'CAPABILITY_INPUT_INVALID'});for(const field of capability.inputSchema.required||[])if(input[field]===undefined||input[field]===null||input[field]==='')throw Object.assign(new Error(`Capability input requires ${field}`),{code:'CAPABILITY_INPUT_INVALID'});if(capabilityId==='research.extend'){const focus=String(input.focus||'').trim(),sourceRef=input.sourceRef?String(input.sourceRef):null,evidenceRef=input.evidenceRef?String(input.evidenceRef):null;if(Buffer.byteLength(focus,'utf8')>500||sourceRef?.length>200||evidenceRef?.length>200||(!focus&&!sourceRef&&!evidenceRef))throw Object.assign(new Error('research.extend requires a valid focus or subject reference'),{code:'CAPABILITY_INPUT_INVALID'});return{focus,sourceRef,evidenceRef};}if(capabilityId==='context.add'){const name=String(input.name||''),content=String(input.content||'');if(!name||!content||content.length>1_000_000)throw Object.assign(new Error('Context input is invalid'),{code:'CAPABILITY_INPUT_INVALID'});return{name,content};}if(capabilityId==='question.change'){const text=String(input.text||'').trim();if(!text||text.length>16_384)throw Object.assign(new Error('Question input is invalid'),{code:'CAPABILITY_INPUT_INVALID'});return{text};}return structuredClone(input);}
