import assert from 'node:assert/strict';
import { buildInteractiveDataModel, buildInteractiveSurface } from '../interop/a2ui/projection.mjs';
import { validateA2UISurface } from '../interop/a2ui/validator.mjs';
import { createInteractiveResultHarness } from '../harnesses/interactive-result.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';

const synthesis={id:'synthesis-audit',type:'SynthesisPlan',data:{objective:'Проверить интерактивный результат'}};
const data={id:'data-audit',type:'DataArtifact',runId:'run-a2ui-audit',data:{title:'Проверяемый результат',columns:['Evidence ID','Наблюдение','Источник'],rows:[['E1','Стабильная строка','fixture.md']],structuredRows:[{rowId:'row-a',values:['E1','Стабильная строка','fixture.md']}],numericMetrics:[['evidence_count',1,'факт','evidence']],insights:['Роль определяет, что важно'],provenance:{rows:[{rowId:'row-a',rowIndex:0,evidenceIds:['E1'],claimIds:['C1'],sourceTitle:'fixture.md'}],metrics:[{metricId:'metric-a',metricKey:'evidence_count',kind:'derived-metric',origin:'evidence',evidenceIds:['E1'],claimIds:['C1']}],insights:[{insightId:'insight-a',insightIndex:0,kind:'interpretation',evidenceIds:[],claimIds:[]}]}}};
const model=buildInteractiveDataModel(data);
assert.equal(model.rows['row-a'].values[1],'Стабильная строка');
assert.equal(model.metrics['metric-a'].value,1);
assert.equal(model.insights['insight-a'].kind,'interpretation');
const surface=buildInteractiveSurface(data,{surfaceId:'surface-audit'});
assert.equal(surface.catalogId,'agentsuite://catalog/interactive-result/v1');
assert.equal(surface.protocolVersion,'1.0');
assert.doesNotThrow(()=>validateA2UISurface(surface.messages,{dataModel:surface.dataModel}));
assert.equal(surface.messages[0].createSurface.components.find(item=>item.id==='root').component,'Column');
assert.ok(surface.messages[0].createSurface.components.every(item=>!['Button','Image','Video','AudioPlayer','Html'].includes(item.component)));
assert.throws(()=>validateA2UISurface([{version:'v1.0',createSurface:{surfaceId:'bad',catalogId:surface.catalogId,components:[{id:'root',component:'Unknown',children:[]}]}}]),/unknown component/);
assert.throws(()=>validateA2UISurface([{version:'v1.0',createSurface:{surfaceId:'bad',catalogId:surface.catalogId,components:[{id:'root',component:'Column',children:['missing']}]}}]),/missing child/);
const reordered=structuredClone(data);reordered.data.rows.reverse();reordered.data.structuredRows.reverse();
assert.equal(buildInteractiveDataModel(reordered).rows['row-a'].values[1],'Стабильная строка','rowId remains authoritative after reorder');
const result=await createInteractiveResultHarness().execute({run:{id:'run-a2ui-audit'},artifacts:[synthesis,data]});
assert.equal(result.artifacts[0].type,'InteractiveResult');
assert.deepEqual(result.artifacts[0].sourceArtifactIds,[synthesis.id,data.id]);
assert.equal(result.artifacts[0].data.provenanceIndex.rows[0].rowId,'row-a');
const renderer=await fs.readFile(path.join(process.cwd(),'public/ui/interactive-result/renderer.js'),'utf8');
assert.doesNotMatch(renderer,/(?:eval|new Function|innerHTML\s*=\s*[^;]*model)/,'renderer does not execute generated code');
const catalog=JSON.parse(await fs.readFile(path.join(process.cwd(),'interop/a2ui/catalog.json'),'utf8'));
assert.equal(catalog.protocolVersion,'1.0');assert.equal(catalog.catalogId,surface.catalogId);assert.ok(catalog.components.Metric&&catalog.components.EvidenceRef);
assert.throws(()=>validateA2UISurface(surface.messages.map(message=>({...message,version:'v0.9'})),{dataModel:surface.dataModel}),/v1.0|version/);
assert.throws(()=>validateA2UISurface(surface.messages.map(message=>({...message,createSurface:{...message.createSurface,catalogId:'agentsuite://catalog/unknown'}})),{dataModel:surface.dataModel}),/catalog/);
console.log('a2ui audit: v1.0 envelope · catalog allowlist · grounded bindings · stable Data IDs · safe renderer · PASS');
