import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { JSDOM } from 'jsdom';
import { buildInteractiveSurface } from '../interop/a2ui/projection.mjs';
import { renderInteractiveResult } from '../public/ui/interactive-result/renderer.js';

const fixture={id:'data-ux',runId:'run-ux',type:'DataArtifact',data:{title:'Почему команда не выполняет план?',columns:['Факт','Наблюдение','Источник'],rows:[['E2','Вторая причина','team.md'],['E1','Первая причина','plan.md']],structuredRows:[{rowId:'row-b',values:['E2','Вторая причина','team.md']},{rowId:'row-a',values:['E1','Первая причина','plan.md']}],numericMetrics:[['Доля задач',37,'%']],insights:['Риск требует отдельного владельца'],provenance:{rows:[{rowId:'row-b',rowIndex:0,evidenceIds:['E2'],claimIds:['C2'],sourceTitle:'team.md'},{rowId:'row-a',rowIndex:1,evidenceIds:['E1'],claimIds:['C1'],sourceTitle:'plan.md'}],metrics:[{metricId:'metric-share',origin:'evidence',evidenceIds:['E1'],claimIds:['C1']}],insights:[{insightId:'insight-risk',kind:'interpretation',claimIds:['C1']}]} }};
const dom=new JSDOM('<main id="host"></main>');
const host=dom.window.document.querySelector('#host');
const surface=buildInteractiveSurface(fixture,{surfaceId:'surface-ux'});
const opened=[];
renderInteractiveResult(host,{data:surface},{onEvidence:id=>opened.push(id)});
assert.equal(host.querySelectorAll('[role="tab"]').length,4,'four stable exploration sections are visible');
assert.match(host.textContent,/Обзор/);
host.querySelector('[data-tab="facts"]').click();
assert.match(host.textContent,/ФАКТ/,'Facts tab changes visible content');
host.querySelector('[data-provenance-kind="row"]').click();
assert.match(host.textContent,/Утверждения/,'fact provenance opens locally');
host.querySelector('[data-close-provenance]').click();
host.querySelector('[data-tab="data"]').click();
const input=host.querySelector('[data-table-filter]');input.value='Первая';input.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
assert.match(host.textContent,/Первая причина/);assert.doesNotMatch(host.textContent,/Вторая причина/,'local filtering does not require Runtime');
host.querySelector('[data-tab="sources"]').click();
host.querySelector('[data-evidence="E1"]').click();assert.deepEqual(opened,['E1'],'evidence uses an explicit safe callback');
const app=await fs.readFile(path.join(process.cwd(),'public/ui/app.js'),'utf8');
assert.match(app,/resultHistory/);assert.match(app,/showEvidence/);assert.match(app,/currentRunId/);assert.match(app,/screen\('history'\)/);
const styles=await fs.readFile(path.join(process.cwd(),'public/ui/interactive-result/interactive-result.css'),'utf8');
assert.match(styles,/prefers-reduced-motion|ir-tabs/,'interactive controls have a bounded visual contract');
console.log('ux audit: ask → watch → explore → verify → history · interactive tabs/filter/provenance/evidence · PASS');
