import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { JSDOM } from 'jsdom';
import { buildInteractiveSurface } from '../interop/a2ui/projection.mjs';
import { renderInteractiveResult } from '../public/ui/interactive-result/renderer.js';
import { HUMAN_STAGE_LABELS, ObservationMode } from '../public/ui/observation/observation-mode.js';

const fixture={id:'data-ux',runId:'run-ux',type:'DataArtifact',data:{title:'Почему команда не выполняет план?',columns:['Факт','Наблюдение','Источник'],rows:[['E2','Вторая причина','team.md'],['E1','Первая причина','plan.md']],structuredRows:[{rowId:'row-b',values:['E2','Вторая причина','team.md']},{rowId:'row-a',values:['E1','Первая причина','plan.md']}],numericMetrics:[['Доля задач',37,'%']],insights:['Риск требует отдельного владельца'],provenance:{rows:[{rowId:'row-b',rowIndex:0,evidenceIds:['E2'],claimIds:['C2'],sourceTitle:'team.md'},{rowId:'row-a',rowIndex:1,evidenceIds:['E1'],claimIds:['C1'],sourceTitle:'plan.md'}],metrics:[{metricId:'metric-share',origin:'evidence',evidenceIds:['E1'],claimIds:['C1']}],insights:[{insightId:'insight-risk',kind:'interpretation',claimIds:['C1']}]} }};
const dom=new JSDOM('<main id="host"></main>');
const host=dom.window.document.querySelector('#host');
const surface=buildInteractiveSurface(fixture,{surfaceId:'surface-ux'});
const opened=[];
renderInteractiveResult(host,{data:surface},{onEvidence:id=>opened.push(id)});
assert.equal(host.querySelectorAll('[role="tab"]').length,4,'four stable exploration sections are visible');
assert.match(host.textContent,/Обзор/);
host.querySelector('[data-tab="facts"]').click();
assert.match(host.textContent,/ФАКТ/,'Facts tab changes visible content');
host.querySelector('[data-provenance-kind="row"]').click();
assert.match(host.textContent,/Утверждения/,'fact provenance opens locally');
host.querySelector('[data-close-provenance]').click();
host.querySelector('[data-tab="data"]').click();
const input=host.querySelector('[data-table-filter]');input.value='Первая';input.dispatchEvent(new dom.window.Event('input',{bubbles:true}));
assert.match(host.textContent,/Первая причина/);assert.doesNotMatch(host.textContent,/Вторая причина/,'local filtering does not require Runtime');
host.querySelector('[data-tab="sources"]').click();
host.querySelector('[data-evidence="E1"]').click();assert.deepEqual(opened,['E1'],'evidence uses an explicit safe callback');
const observationDom=new JSDOM('<main id="observation"></main>');
globalThis.window=observationDom.window;window.matchMedia=()=>({matches:false});
const fullIntent='Как проверить, что очень длинный вопрос о согласованности структуры наблюдения не обрывается посередине слова и остаётся доступным для проверки в Inspector, когда пользователь просит подробно объяснить зависимость между Flow, источниками, фактами, результатами, действиями модели и контекстом решения для всей команды?';
const observationState={runId:'observation-ux',status:'running',intent:fullIntent,startedAt:new Date().toISOString(),elapsedMs:0,activeStage:'research',contextWorld:{roots:[],sources:[]},stages:Object.keys(HUMAN_STAGE_LABELS).map((id,index)=>({id,label:id,state:index<3?'completed':id==='research'?'active':'future',result:{artifacts:[],reusedArtifacts:[]}})),evidence:{items:[]},outputs:[],capabilities:[],agentActions:[],terminalRecords:[],safeInputEvents:[],artifactRefs:[],dependencies:[],role:{id:'product-owner',label:'Продуктовый ракурс'},system:{process:{rssMiB:123},gpu:[{name:'Test GPU',utilization:42}]}};
const observation=new ObservationMode(observationDom.window.document.querySelector('#observation'));observation.render(observationState);
const mainFlow=[...observationDom.window.document.querySelectorAll('[data-flow-region="main"] [data-flow-stage]')];
assert.deepEqual(mainFlow.map(node=>node.dataset.flowStage),['intent-discovery','intent','brief','research','validation','synthesis','data'],'main Flow contains only seven human research stages');
assert.deepEqual(mainFlow.map(node=>node.textContent.trim()),['ПОИСК ВОПРОСА','ВОПРОС','КОНТЕКСТ','ПОИСК','ПРОВЕРКА','ВЫВОД','ДАННЫЕ'],'Flow preserves distinct human research labels');
assert.equal(mainFlow.some(node=>node.dataset.flowStage==='interactive-result'),false,'InteractiveResult is not presented as a research continuation');
const resultItems=[...observationDom.window.document.querySelectorAll('[data-flow-region="results"] [data-flow-stage]')];
assert.equal(observationDom.window.document.querySelector('[data-flow-region="results"]>small').textContent.trim(),'РЕЗУЛЬТАТЫ','result group has an explicit human heading');
assert.deepEqual(resultItems.map(node=>node.textContent.trim()),['ИНТЕРАКТИВНО','РАССКАЗ','ТАБЛИЦА','СЛАЙДЫ'],'result group exposes exactly four distinct formats');
assert.deepEqual(resultItems.map(node=>node.dataset.canonicalStage),['interactive-result','narrative','data','slides'],'every result format derives status from a canonical stage');
assert.equal(resultItems.find(node=>node.dataset.flowStage==='data-table').dataset.canonicalStage,'data','Table is a view of the existing DataArtifact stage');
assert.equal([...observationDom.window.document.querySelectorAll('[data-flow-stage]')].some(node=>node.textContent.trim()==='РЕЗУЛЬТАТ'),false,'no generic collapsed result label is presented as a result item');
const displayIntent=observationDom.window.document.querySelector('.intent-question h2').textContent;assert.match(displayIntent,/…$/,'display Intent uses explicit ellipsis');assert.doesNotMatch(displayIntent,/сло…$/,'display Intent does not cut a word');
observationDom.window.document.querySelector('.intent-question').click();assert.match(observationDom.window.document.querySelector('.inspector-lens').textContent, /остаётся доступным для проверки в Inspector/,'Inspector receives the complete canonical Intent');assert.match(observationDom.window.document.querySelector('.inspector-lens').textContent, /действиями модели и контекстом решения/,'Inspector retains the complete canonical Intent tail');
observationDom.window.document.querySelector('[data-flow-stage="interactive-result"]').click();assert.match(observationDom.window.document.querySelector('.inspector-lens').textContent,/ИНТЕРАКТИВНО/,'Inspector retains the canonical InteractiveResult stage');
const app=await fs.readFile(path.join(process.cwd(),'public/ui/app.js'),'utf8');
assert.match(app,/resultHistory/);assert.match(app,/showEvidence/);assert.match(app,/currentRunId/);assert.match(app,/screen\('history'\)/);
const styles=await fs.readFile(path.join(process.cwd(),'public/ui/interactive-result/interactive-result.css'),'utf8');
assert.match(styles,/prefers-reduced-motion|ir-tabs/,'interactive controls have a bounded visual contract');
const appStyles=await fs.readFile(path.join(process.cwd(),'public/ui/app.css'),'utf8');
assert.match(appStyles,/\.narrative-surface h1/,'Narrative owns document typography');
assert.match(appStyles,/\.data-surface h1/,'Data owns compact table typography');
assert.doesNotMatch(appStyles,/\.narrative-surface h1\{[^}]*6vw/,'Narrative does not inherit title-slide scale');
assert.match(appStyles,/\.intent-question h2\{[^}]*-webkit-line-clamp:2/,'Observation intent is constrained to its own two-line region');
assert.match(appStyles,/\.flow-main\{[^}]*repeat\(7,/,'Observation declares all seven research-flow slots explicitly');
assert.match(appStyles,/\.flow-results-grid\{[^}]*repeat\(4,/,'Observation declares four desktop result-materialization slots explicitly');
assert.match(appStyles,/\.intent-strip\{[^}]*grid-template-columns:minmax\(0,1fr\) auto/,'Observation reserves a distinct telemetry column');
assert.match(appStyles,/\.output-rail>button/,'Observation results have a dedicated compact rail rule');
assert.match(app,/#windowControl'\)\.addEventListener\('click'/,'window close control has an explicit click boundary');
assert.match(app,/window\.poDesktop\?\.close/,'Electron close capability remains the preferred window-close path');
console.log('ux audit: ask → watch → explore → verify → history · interactive tabs/filter/provenance/evidence · PASS');
