import {capabilityAction,displayCapabilitiesForRole} from '../../core/capabilities.mjs';
export const SURFACE_KINDS=Object.freeze(['activity','workspace','source','evidence','validation','table','chart','comparison','diff','story','presentation','choice','approval','input','progress']);
export const DEFAULT_RENDERER_CAPABILITIES=Object.freeze({surfaces:[...SURFACE_KINDS],interactions:['select','expand','collapse','invoke','submit','sort','filter','navigate']});
const clean=value=>value==null?null:structuredClone(value);
const provenance=(sourceRefs,eventSequence=null,artifactId=null)=>({sourceRefs:[...sourceRefs],...(Number.isSafeInteger(eventSequence)?{eventSequence}:{}),...(artifactId?{artifactId}:{})});
const surface=({id,kind,scope,sourceRefs=[],truth=null,lifecycle='settled',content={},actions=[],requiredRendererCapabilities=[kind],presentationHints={density:'compact',preferredRegion:'secondary'}})=>({id,kind,scope,sourceRefs:[...sourceRefs],provenance:truth||provenance(sourceRefs),lifecycle,content:clean(content),actions:actions.filter(Boolean),requiredRendererCapabilities:[...requiredRendererCapabilities],presentationHints:{...presentationHints}});
const artifactKind=type=>({Narrative:'story',DataArtifact:'table',Presentation:'presentation'}[type]||null);
const interruptKind=kind=>kind==='context-request'||kind==='clarification'?'input':kind==='confirmation'?'choice':kind;
const roleLabel=(roleId,kind)=>roleId==='cto'?'Проверить технический риск':roleId==='product-owner'?'Уточнить влияние':kind==='source'?'Исследовать источник глубже':'Проверить дальше';
export function deriveSurfaceActions({surface:target,session,capabilities=null}={}){if(!target||!session)return[];const allowed=!capabilities||capabilities.some(item=>(typeof item==='string'?item:item.id)==='research.extend');if(!allowed||!['source','evidence','validation','workspace'].includes(target.kind))return[];const sourceRef=target.kind==='source'?target.sourceRefs[0]:null,evidenceRef=target.kind==='evidence'?target.sourceRefs[0]:null,hasResearchContext=Boolean((session.research?.evidence||[]).length||(session.research?.sources||[]).length),subjectKey=target.kind==='validation'?'validation':target.kind==='workspace'?'workspace':`${target.kind}:${sourceRef||evidenceRef}`,roleId=session.role?.id||'product-owner',prompt=roleId==='cto'?'Какой технический риск проверить?':roleId==='product-owner'?'Что уточнить с точки зрения влияния?':'Что именно проверить?';return[capabilityAction('research.extend',{runStatus:session.session.status,hasResearchContext,roleId,actionKey:subjectKey,inputBinding:{...(sourceRef?{sourceRef}:{}),...(evidenceRef?{evidenceRef}:{})},label:roleLabel(roleId,target.kind),inputRequest:{title:'Продолжить исследование',fields:[{id:'focus',kind:'text',label:prompt,required:true,constraints:{maxLength:500}}],submitLabel:'Продолжить',sourceRefs:[...target.sourceRefs]}})].filter(Boolean);}
export function projectSurfaces(session,{historical=false}={}){
  if(!session?.session?.runId)return{schemaVersion:1,lastAppliedSequence:0,role:{id:null,displayCapabilities:[]},items:[]};
  const lifecycle=historical||['completed','failed','cancelled','interrupted'].includes(session.session.status)?'historical':'settled',items=[],sequence=Number(session.session.lastSequence||0),roleId=session.role?.id||'product-owner',displayCapabilities=displayCapabilitiesForRole(roleId),status=session.session.status,pending=session.ui?.pendingInteraction;
  const runActions=[capabilityAction('run.cancel',{runStatus:status}),capabilityAction('run.retry',{runStatus:status}),capabilityAction('run.branch',{runStatus:status}),capabilityAction('context.add',{runStatus:status}),capabilityAction('question.change',{runStatus:status})];
  items.push(surface({id:`surface:activity:${session.session.runId}`,kind:'activity',scope:'run',sourceRefs:[session.session.runId],truth:provenance([session.session.runId],sequence),lifecycle:status==='running'?'active':lifecycle,content:session.activity,actions:runActions,presentationHints:{emphasis:'primary',density:'compact',preferredRegion:'primary',roleLens:roleId}}));
  const workspaceSurface=surface({id:`surface:workspace:${session.session.runId}`,kind:'workspace',scope:'run',sourceRefs:[session.session.runId],truth:provenance([session.session.runId],sequence),lifecycle,content:session.workspace,presentationHints:{density:'compact',preferredRegion:'secondary'}});workspaceSurface.actions=deriveSurfaceActions({surface:workspaceSurface,session});items.push(workspaceSurface);
  for(const source of session.research?.sources||[]){const id=String(source.sourceId||source.id||'');if(id){const value=surface({id:`surface:source:${id}`,kind:'source',scope:'source',sourceRefs:[id],lifecycle:source.state==='opened'?'active':lifecycle,content:source});value.actions=deriveSurfaceActions({surface:value,session});items.push(value);}}
  for(const evidence of session.research?.evidence||[]){const id=String(evidence.id||evidence.evidenceId||'');if(id){const value=surface({id:`surface:evidence:${id}`,kind:'evidence',scope:'evidence',sourceRefs:[id,...(evidence.sourceId?[String(evidence.sourceId)]:[])],lifecycle,content:evidence});value.actions=deriveSurfaceActions({surface:value,session});items.push(value);}}
  if((session.research?.validation||[]).length){const value=surface({id:`surface:validation:${session.session.runId}`,kind:'validation',scope:'validation',sourceRefs:(session.research.validation||[]).map(item=>String(item.evidenceId||item.id||'')).filter(Boolean),lifecycle,content:{items:session.research.validation}});value.actions=deriveSurfaceActions({surface:value,session});items.push(value);}
  for(const artifact of session.outputs?.artifacts||[]){const kind=artifactKind(artifact.type);if(kind)items.push(surface({id:`surface:artifact:${artifact.artifactId}`,kind,scope:'artifact',sourceRefs:[artifact.artifactId],truth:provenance([artifact.artifactId],sequence,artifact.artifactId),lifecycle,content:artifact,presentationHints:{emphasis:'primary',density:'comfortable',preferredRegion:'primary'}}));}
  if(pending){const kind=interruptKind(pending.kind),action=capabilityAction('run.respond-to-interrupt',{runStatus:status,pendingInterrupt:true,inputBinding:{interruptRef:pending.interruptId}});items.push(surface({id:`surface:interrupt:${pending.interruptId}`,kind,scope:'interrupt',sourceRefs:[pending.interruptId],truth:provenance([pending.interruptId],sequence),lifecycle:historical?'historical':'active',content:pending,actions:[action],presentationHints:{emphasis:'primary',density:'comfortable',preferredRegion:'primary'}}));}
  return{schemaVersion:1,lastAppliedSequence:sequence,role:{id:roleId,displayCapabilities},items:items.sort((a,b)=>a.id.localeCompare(b.id))};
}
export function mountableSurfaces(projection,rendererCapabilities=DEFAULT_RENDERER_CAPABILITIES){const supported=new Set(rendererCapabilities?.surfaces||[]);return(projection?.items||[]).filter(item=>item.requiredRendererCapabilities.every(value=>supported.has(value)));}
export function reconcileSurfaceProjection(current,incoming){const prior=Number(current?.lastAppliedSequence||0),next=Number(incoming?.lastAppliedSequence||0);if(next<=prior)return{state:current,effect:'stale'};if(next>prior+1)return{state:incoming,effect:'reconciled-gap'};return{state:incoming,effect:'applied'};}
